### ISSUE TITLE
Hmmbuild parse error

### ISSUE THREAD

**Issue by nadine-zakkak** [EddyRivasLab/hmmer#189] opened 2020-05-05 22:01 UTC
Hello

I am trying to build a pHMM for a multiple sequence alignment amino acid sequences that I downloaded from the Los Alamos HIV Sequence Database. I want to later use this pHMM in the hivmmer tool by kantorlab. But I am getting the following error:

```
Alignment input parse error:
   one or more invalid sequence characters
   while reading aligned FASTA file HIV1_ALL_2018_pol_PRO.fasta
   at or near line 39
```
It is working fine with the DNA multiple sequence alignment file. 

Any ideas why I am getting this error and how I can fix it?

Thank you

**Comment by npcarter** [comment] 2020-05-05 22:45
Hello,

**Comment by npcarter** [comment] 2020-05-05 22:48
Hello,  there are two likely possibilities for what's causing your problem.  Possibility 1 is that there is, in fact, a character on or near line 39 that isn't in the alphabet FAST uses for amino acid sequences, but I'll assume you checked  that.  Possibility 2 is that hmmbuild's code that attempts to auto-detect the alphabet your FASTA file is using is getting it wrong.  The --amino option to hmmbuild tells hmmbuild to assume the input alignment is an amino-acid alignment instead of guessing.  Could you try re-running hmmbuild on your file with that flag passed? (hmmbuild --amino <file>)

**Comment by nadine-zakkak** [comment] 2020-05-06 18:28
There is in fact a "#" at line 39 that, up to my knowledge, is not part of the alphabet known to be used in FASTA amino acid sequences. Nevertheless, I tried running it with the --amino option and I still got the same error. So I'm assuming the error is due to the # in my file.

**Comment by npcarter** [comment] 2020-05-06 18:54
Ok, sounds like the problem is in the data file.  I'm going to close this issue, feel free to open another one if you still have problems after fixing the file.

**Closed by npcarter** 2020-05-06 18:54 UTC
