### ISSUE TITLE
nhmmer -A output alignment does not have the correct number of match states

### ISSUE THREAD

**Issue by kad-ecoli** [EddyRivasLab/hmmer#193] opened 2020-06-21 01:24 UTC
```
$ cat seq.fasta
>4ojiA
CCGCCTAACACTGCCAGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGCGG
```
I am using nhmmer to search this sequence (seq.fasta) with 52 nucleotides against a small database of 27 sequences using the following command:
```bash
$ nhmmer -A test.sto --hmmout test.hmm --noali --tblout test.tblout --cpu 1 --watson seq.fasta test.db
$ esl-reformat a2m test.sto > test.a2m
```
The output test.hmm correctly includes 52 match states.
However, the output alignment test.sto and test.a2m only includes 50 match states [-ATCG], as the positions for the first and last residue in the query sequence is missing in the output alignment.

```bash
$ head test.a2m
>URS000080DF17_32630/2-53 [subseq from] URS000080DF17_32630
CGCCTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGCG
>URS0000D6878F_12908/2-51 [subseq from] URS0000D6878F_12908
-GCCTAACACTGCCAGtgCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC-
>URS0000D66A77_4558/2-51 [subseq from] URS0000D66A77_4558
-GCCTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC-
>URS0000D6C74A_4558/2-51 [subseq from] URS0000D6C74A_4558
-GCTTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC-
>URS0000D69167_4558/2-51 [subseq from] URS0000D69167_4558
-GCCTAACACTGCCAatGCCGGTCCCAAGCCCGGATAGAAGTGGAGGGGGC-
```

My input and output files are attached.
[test.zip](https://github.com/EddyRivasLab/hmmer/files/4808786/test.zip)

Another related question: is it possible to include the query sequence in the output alignment from the -A option? Thank you.

**Comment by cryptogenomicon** [comment] 2020-06-21 12:30
Hi, you don't say what you think the problem is. I'm guessing that you mean that you expected the output alignments to have 52 match states. HMMER does local alignment, not global alignment, so output alignments will have <=M match states for a model of length M.

To include the query, you can use `hmmalign` to align any set of sequences you want to a model.

Hope this helps!

**Comment by kad-ecoli** [comment] 2020-06-21 19:59
I am still not sure how to merge seq.fasta into test.sto/test.a2m. hmmalign input is an HMM and a sequence file, not a sequence file and an alignment file.

**Comment by cryptogenomicon** [comment] 2020-06-21 20:04
One way is to convert the alignment file to FASTA and append the query, for example with something like:
```
    esl-reformat fasta test.a2m > newfile
    cat seq.fasta >> newfile
    hmmalign your.hmm newfile
```

**Comment by kad-ecoli** [comment] 2020-06-21 20:46
Unfortunately, apparently esl-reformat cannot parse a2m.
```bash
$ esl-reformat fasta nhmmer.a2m

>URS000080DF17_32630/2-53 [subseq from] URS000080DF17_32630
CGCCTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGCG
Parse failed (sequence file 4ojiA/MSA/nhmmer.a2m):
Line 4: illegal character -
```

Even if esl-reformat could have de-aligned test.a2m into fasta, this does not address the issue, because such conversion completely destroy the original alignment from nhmmer. 

-A output alignment of jackhmmer always includes the query sequence. I am not sure why there is no similar way to generate an nhmmer alignment with query.

**Comment by cryptogenomicon** [comment] 2020-06-21 20:49
Sorry. Make it `esl-reformat --informat a2m nhmmer.a2m`, to force it to see that the file is an a2m file, not fasta.

**Comment by kad-ecoli** [comment] 2020-06-21 20:55
I believe your meant ``esl-reformat --informat a2m fasta nhmmer.a2m``. As mentioned above, this will disrespect the nhmmer alignment. It also does not correctly convert lower cases to upper cases. 

What I am hoping to find is something like the jackhmmer -A option, which will generate the alignment with the query. The current nhmmer -A option is not particularly helpful in my case: if we do not not where a position in the resulting alignment corresponds to in the query sequence, we cannot use the alignment.

**Comment by cryptogenomicon** [comment] 2020-06-21 21:01
Yes, `esl-reformat --informat a2m fasta nhmmer.a2m`. `nhmmer` and `hmmalign` should give you the same alignment; you're aligning to the same model. 

Have you tried what I suggested? It will do essentially what jackhmmer -A does to include the query.

**Comment by kad-ecoli** [comment] 2020-06-21 21:12
No, it does not give the same alignment, even when aligning to the same hmm model.
```bash
$ cat seq.fasta > newfile
$ esl-reformat --informat a2m fasta test.a2m >> newfile
$ hmmalign --outformat a2m  test.hmm newfile |head
>4ojiA
CCGCCTAACACTGCCAGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGCGG
>URS000080DF17_32630/2-53 [subseq from] URS000080DF17_32630
-CGCCTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGCG-
>URS0000D6878F_12908/2-51 [subseq from] URS0000D6878F_12908
--GCCTAACACTGCCAGtgCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC--
>URS0000D66A77_4558/2-51 [subseq from] URS0000D66A77_4558
--GCCTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC--
>URS0000D6C74A_4558/2-51 [subseq from] URS0000D6C74A_4558
g---CTTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC--
```
As mentioned in the beginning of this thread, test.hmm was generated by nhmmer using --hmmout.
The 4th hit has very different alignment compare to the original nhmmer alignment in test.a2m
```bash
$ head -8 test.a2m 
>URS000080DF17_32630/2-53 [subseq from] URS000080DF17_32630
CGCCTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGCG
>URS0000D6878F_12908/2-51 [subseq from] URS0000D6878F_12908
-GCCTAACACTGCCAGtgCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC-
>URS0000D66A77_4558/2-51 [subseq from] URS0000D66A77_4558
-GCCTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC-
>URS0000D6C74A_4558/2-51 [subseq from] URS0000D6C74A_4558
-GCTTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC-
```

**Comment by cryptogenomicon** [comment] 2020-06-21 21:15
You can get slightly different results, depending on details, but there's not much reason to favor one as more correct than the other.

Closing this now.

**Closed by cryptogenomicon** 2020-06-21 21:15 UTC

**Comment by kad-ecoli** [comment] 2020-06-21 21:22
I am sorry if there is no true solution. The lack of the query in the output alignment of a sequence search should be considered a bug, not a feature. If you or your team does not have resource to address this issue, I will try to implement a workaround.

**Comment by cryptogenomicon** [comment] 2020-06-21 21:23
Feel free, and good luck.

**Comment by kad-ecoli** [comment] 2020-06-21 21:30
By the way, in the above case, the "obvious" correct answer should be. You might want to check why hmmalign will consider the first G in the 4th hit an insertion state rather than a match state.

```
>4ojiA
CCGCCTAACACTGCCAGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGCGG
>URS000080DF17_32630/2-53 [subseq from] URS000080DF17_32630
-CGCCTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGCG-
>URS0000D6878F_12908/2-51 [subseq from] URS0000D6878F_12908
--GCCTAACACTGCCAGtgCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC--
>URS0000D66A77_4558/2-51 [subseq from] URS0000D66A77_4558
--GCCTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC--
>URS0000D6C74A_4558/2-51 [subseq from] URS0000D6C74A_4558
--GCTTAACACTGCCAatGCCGGTCCCAAGCCCGGATAAAAGTGGAGGGGGC--
```
