### ISSUE TITLE
nhmmer requests negative memory when request exceeds maximum int size 

### ISSUE THREAD

**Issue by xonq** [EddyRivasLab/hmmer#213] opened 2020-12-09 13:56 UTC
I am using a program Orthofiller, which leverages profile hmms of orthogroups to search assemblies (hmmdb) for missing genes using `nhmmer`. When using decently sized fungal genomes (> 60 Mb) nhmmer fails with:
```
Fatal exception (source file p7_hmmwindow.c, line 56):
realloc for size 77175936 failed 
Aborted
```

I believe this happens because the requested realloc size is calculated by multiplying 655360000 by 4 (Line 56 in the p7_hmmwindow source code), which makes the int value larger than maximum int size and then requests negative memory. Changing the type of that variable causes downstream errors in other C files, including `p7_hmm_window_list_s`

**Comment by cryptogenomicon** [comment] 2020-12-09 14:10
Looks like your machine ran out of memory. You'll need to change what you're doing to use less RAM at once, or move to a machine with more RAM.

**Comment by xonq** [comment] 2020-12-09 14:15
I reported this with the supercomputer staff because I requested over a terabyte of memory and this error came up, though the request should be within limits. They believe it is the code, not the RAM requesting system for the job. The hmmer documentation states these errors are present for `phmmer` and that developers are working on a "memory efficient algorithm" - is this an instance of that error?

**Comment by cryptogenomicon** [comment] 2020-12-09 14:23
The error is the result of the system realloc() reporting that it is unable to successfully allocate memory, which means the system ran out of RAM.

I didn't understand your comment about "655360000" in the p7_hmmwindow_new() code. That seems like an unlikely number. If you're really doing something where you have 655 million hits to one target sequence, yes, you might see issues we haven't anticipated. But 655 million different hits shouldn't be possible, in a target sequence of only 60Mb.

**Comment by xonq** [comment] 2020-12-09 14:26
okay, this is good to know. I apologize if i was not making sense, I was repeating what the investigator reported and I do not write in C, so Im not familiar. I will close or report back following correspondence.

**Comment by ZQyou** [comment] 2020-12-09 14:58
@cryptogenomicon I am the OSC staff.  I don't understand nhmmer but here is my debugging output:

```
# nhmmer :: search a DNA model, alignment, or sequence against a DNA database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query file:                      /fs/ess/scratch/PZS0710/zyou/help/osu10393_orthofiller_INC0353364/orthofiller_2011/working/orthogroups/hmm/OG0006269.hmm
# target sequence database:        /fs/ess/scratch/PZS0710/zyou/help/osu10393_orthofiller_INC0353364/orthofiller_2011/working/hmmdb/athtb5.mask.clean.fsa.aa.fasta.hmmdb
# hits tabular output:             /fs/ess/scratch/PZS0710/zyou/help/osu10393_orthofiller_INC0353364/orthofiller_2011/working/orthogroups/hits/athtb5.mask.clean.fsa.aa.fasta/OG0006269.athtb5.mask.clean.fsa.aa.fasta.hits
# input query is asserted as:      DNA
# number of worker threads:        1
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       OG0006269_NucAlignment  [M=396]
10000	10000	56
40000	40000	56
160000	160000	56
640000	640000	56
2560000	2560000	56
10240000	10240000	56
40960000	40960000	56
163840000	163840000	56
655360000	655360000	56
Fatal exception (source file p7_hmmwindow.c, line 57):
realloc for size 771751936 failed
```

I printed out `list->size`, `list->count` and `sizeof(P7_HMM_WINDOW))`  in `p7_hmmwindow_new`.  I also tried change the variable type in `P7_HMM_WINDOWLIST` to `size_t` or `unsigned int` and the error is gone. I believe the reallocation error is caused by a negative number of `list->size`.

**Comment by cryptogenomicon** [comment] 2020-12-09 15:04
If list->size there has rolled over the maximum size of an int and gone negative, you have other problems. I don't see how that could possibly happen. There's no plausible way that you can have >2 billion hits in the same target sequence, which is what would have to be happening. What exactly is the comparison here -- what profile against what sequence? How long is the profile, and how long is the sequence? Is the target sequence database actually DNA sequence -- the filename looks like it's protein?

**Comment by ZQyou** [comment] 2020-12-09 16:15
Here are the links to the input files:

https://osu.box.com/s/hfz755zodrfgm5yrols7lre5zsegl3b7
https://osu.box.com/s/22hokjwvrcdegcsabxym2kymp9h95a0f

The links will expire on Dec. 13, 2020. 

I think @xonq can provide more details.

**Comment by xonq** [comment] 2020-12-09 16:17
Thank you for posting the files @ZQyou.

The script calling nhmmer is [orthofiller.py](https://github.com/mpdunne/orthofiller). Though that appears to be a protein database, I abstracted the code orthofiller is running and verified the hmmdb is binary hmmerfm derived directly from the assembly. The <ORTHOGROUP.hmm> query is roughly 70 kB and the <ASSEMBLY.hmmdb> is 100 MB. The `makehmmerdb` command:
```
makehmmerdb --block_size 10 <ASSEMBLY> <ASSEMBLY.hmmdb>
```

The nhmmer command is:
```
nhmmer --dna --cpu 1 --tblout <OUTPUT> <ORTHOGROUP.hmm> <ASSEMBLY.hmmdb>
```

The <ORTHOGROUP.hmm> header indicates few sequences:
```
NAME  OG0006269_NucAlignment
LENG  396
MAXL  3686
ALPH  DNA
RF    no
MM    no
CONS  yes
CS    no
MAP   yes
DATE  Tue Dec  8 19:48:32 2020
NSEQ  11
EFFN  2.838623
```

**Comment by cryptogenomicon** [comment] 2020-12-09 16:40
Thanks. Could you also provide the FASTA file `athtb5.mask.clean.fsa.aa.fasta`, before the `makehmmerdb` step?

**Comment by xonq** [comment] 2020-12-09 16:48
> Thanks. Could you also provide the FASTA file `athtb5.mask.clean.fsa.aa.fasta`, before the `makehmmerdb` step?

Yes, the file is `athtb5.mask.clean.fsa` and is [here](https://osu.box.com/s/dk0yi94zvs13nnv75taq7v0wryblkux2)
Orthofiller just uses the extracted protein fasta name as the base name for the hmmdb output, but I've verified it is running the assembly and have reproduced the error by isolating the commands on the assembly.

**Comment by cryptogenomicon** [comment] 2020-12-09 17:01
OK, this works fine:

```
   nhmmer --cpu 1 OG0006269.hmm athtb5.mask.clean.fsa
```

and so does this:

```
   ln -s athtb5.mask.clean.fsa foo.fa
   makehmmerdb foo.fa  foo.db
   nhmmer --cpu 1 OG0006269.hmm foo.db 
```

but this fails with the error you reported, when I use your binary db file:

```
   nhmmer --cpu 1 OG0006269.hmm athtb5.mask.clean.fsa.aa.fasta.hmmdb 
```

and this also fails:

```
    makehmmerdb --block_size 10 foo.fa  foo.db
    nhmmer --cpu 1 OG0006269.hmm foo.db 
```

So it looks like we must have a bug specific to using `--block_size 10` instead of the default for `makehmmerdb`. I'll have to look into it further with the author of `nhmmer`. Is there a good reason to specify this option and change our default? If not, my suggested workaround is to take out the `--block_size 10` option. 

Another suggested workaround (which will probably actually get you better results) is not to mess with our experimental FM-index acceleration of nhmmer at all. Your searches are small. Just do:

```
    nhmmer --cpu 1 OG0006269.hmm athtb5.mask.clean.fsa
```

and search the FASTA file directly.

**Comment by xonq** [comment] 2020-12-09 17:07
Hey this is all great information and I think something that should be easy to implement. I cannot comment on the orthofiller authors' reasoning for using those parameters. Orthofiller was written using `hmmer 3.1b2`, so I manually updated it to newer versions. Their git also isn't active, so I'll just implement these changes myself. Thank you very much for both of your time @ZQyou and @cryptogenomicon.

I'll leave this issue open since you consider this a potential bug, but close whenever you feel is appropriate.

**Comment by cryptogenomicon** [comment] 2020-12-09 23:33
@traviswheeler, could you look into this one? thanks!

**Comment by traviswheeler** [comment] 2020-12-09 23:44
Yup, I'll look into the block_size error soon.  Thanks to @xonq and @ZQyou for the files required to reproduce, and to @cryptogenomicon for diving into this while I've been offline.

**Comment by xonq** [comment] 2020-12-10 03:54
@traviswheeler I may have deleted the assembly (athtb5.clean.mask.fsa) before you got to it - [here is a new link](https://osu.box.com/s/8i6kwkzate7p97m1zynqozvq6fcxd8jc). Ill leave it up until the 13th as well.

thanks for all the great software!
cheers,
zach

**Comment by traviswheeler** [comment] 2020-12-10 23:29
Thanks. I have the file, so you can remove it.

**Comment by traviswheeler** [comment] 2020-12-10 23:39
I spoke too soon.   I was able to retrieve the file you posted most recently (athtb5.clean.mask.fsa), but not the hmm file you posted earlier: OG0006269.hmm

A quick Can you please share that again?

**Comment by xonq** [comment] 2020-12-11 02:34
Yes, [OG0006269.hmm](https://osu.box.com/s/o8q4wmyh0hgepec8qddafx3s3v2k39o9)

**Comment by cryptogenomicon** [comment] 2021-01-17 15:31
Thanks again for the report. We believe this is fixed now in our `develop` branch, and the fix will appear in the next release.

**Closed by cryptogenomicon** 2021-01-17 15:31 UTC
